version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env.example
    volumes:
      - ../backend:/app
      
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env.local.example
    volumes:
      - ../frontend:/app
      - /app/node_modules
